language: python

install:
  - pip3 install pipenv
  - pipenv install
  - export PYTHONPATH=$PWD

script:
  # - python3 tests/test_math_functions.py
  - coverage run -m unittest tests/test_math_functions.py

after_success:
  - bash <(curl -s https://codecov.io/bash)